config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :events, except: [:show]
  resources :universities 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root :to => 'universities#index'
  get 'universities/index2'
  get 'events/saveEventCategory'
  get 'events/loadCategories'
  get 'events/:id', to: 'events#show'
  
  
  
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :university
	has_many :category_events
	has_many :categories, through: :category_events
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    if params[:idUniversity]!=nil
      session[:idUniversity]=params[:idUniversity]
      id=params[:idUniversity]
    else
      id=session[:idUniversity]
    end
    @university=University.find(id)
    @events = @university.events.order(fecha: :asc)
    @categorias=Category.all
    
  end

  def index2
    @events = Event.all.order(fecha: :asc)
  end
  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end
 def loadCategories
    @event=Event.find(params[:id_event])
    @categorias=Category.all
    respond_to do |format|
      format.js
    end
  end

  def saveEventCategory
    idEvent   = params[:event_id]
    idCategory = params[:category_id]
    rta           = params[:checked]
    if rta=="true"
      categoryEvent=CategoryEvent.new
      categoryEvent.event_id=idEvent
      categoryEvent.category_id=idCategory
      categoryEvent.save
    else
      categoryEvent=CategoryEvent.find_by(event_id: idEvent, category_id:idCategory)
      categoryEvent.destroy
    end
    respond_to do |format|
         format.js
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.university_id=session[:idUniversity]
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:id_event, :nombre, :descripcion, :lugar, :fecha, :categoria, :link)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_addCategories.html.erb
<!-- Modal -->
<div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"  id="nameEvent"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">       
        <h4>Categorías</h4>
        <table id="tableCategories" class="table table-striped">
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="container py-5">
   <div class="row">
      <div class="col-md-12">
         <div class="row">
            <div class="col-md-6 mx-auto">
               <!-- form card login -->
               <div class="card rounded-0">
                  <div class="card-header">
                     <h3 class="mb-0">Formulario</h3>
                  </div>
                  <div class="card-body">
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :id_event %>
    <%= form.text_field :id_event, id: :event_id_event, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :event_nombre, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :event_descripcion,:cols => 10, :rows => 5, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :lugar %>
    <%= form.text_field :lugar, id: :event_lugar, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :event_fecha, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, id: :event_link, :class=>'form-control form-control-lg rounded-0' %>
  </div>
  <div class="actions">
    <%= form.submit "Enviar", :class=>'btn btn-success btn-lg float-right'  %>
  </div>
<% end %>
</div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/events/edit.html.erb
<h1>Editar Evento</h1>

<%= render 'form', event: @event %>
<center> 		
<div class="" style="padding-top: 2em">
<%= link_to 'Show', @event, :class=>'btn btn-secondary btn-lg float-center' %> |
<%= link_to 'Back', events_path, :class=>'btn btn-warning btn-lg float-center' %>
</div>
</center>

app/views/events/index.html.erb
<script type="text/javascript">
     function loadCategories(idEvent) {
       $.ajax({
              type: "GET",
              url: '/events/loadCategories',
              data: {
                id_event    : idEvent
             },
             dataType: "script",
             success: function() {
               console.log('ok');
             }
           });

    }

     function saveEventCategory(object,idevent,idcategory){
     var rta=false;
       if($(object).is(":checked")){
               rta=true;
       }
       $.ajax({
              type: "GET",
              url: '/events/saveEventCategory',
              data: {
                event_id    : idevent,
                category_id  : idcategory,
                checked         : rta
             },
             dataType: "script",
             success: function() {
               console.log('ok');
             }
           });

    }
</script>
<p id="notice"><%= notice %></p>
<%= render 'addCategories'%>
<h1>Eventos acádemicos</h1>

<table class="table">
  <thead class="thead-dark text-center">
    <tr>
      <th>Id event</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Lugar</th>
      <th>Fecha</th>
      <th>Categoria</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id_event %></td>
        <td><%= event.nombre %></td>
        <td><%= event.descripcion %></td>
        <td><%= event.lugar %></td>
        <td><%= event.fecha %></td>
        <td>          
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal3" onclick="loadCategories('<%=event.id%>')">
           Asignar
          </button>
        </td>
        <td> <a href="http://<%= event.link %>" target="blank" class="btn btn-outline-success">Acceder</a> </td>
        <td><%= link_to 'Show', event, :class=>'btn btn-info'  %></td>
        <td><%= link_to 'Edit', edit_event_path(event), :class=>'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Nuevo evento', new_event_path, :class=> 'btn btn-success btn-lg' %>
</br></br>
<div class="row ">
<% @events.each do |event| %>
  <div class="col-sm-12 col-md-12 col-lg-6" style="overflow: auto;">
    <div class="card bg-light mb-3">
      <div class="card-header text-center header-color"><%= event.university.nombre %></div>
      <div class="card-body">
        <h5 class="title"><%= event.nombre %></h5>
        <p class="card-text">
          <b>Descripción:</b> <%= event.descripcion %> <br>
          <b>Lugar:</b> <%= event.lugar %> <br>
          <b>Fecha:</b> <%= event.fecha %> <br>

          <b>Categorias:</b> 

          <% @categorias.each do |categoria|%>

            <% categoryEvent=CategoryEvent.find_by(category_id: categoria.id,event_id: event.id) %>
            <%if categoryEvent!=nil %>
             - <%= categoria.nombre %> 
            <%end%>

          <%end%>
          <br>

          <center>
          <a href="http://<%= event.link %>" target="blank" class="btn btn-success" style="width: 100%;font-size: 18px;" >Más información</a>
          </center>
        </p>
      </div>
    </div>
  </div>
<% end %>
</div>
<br>

app/views/events/index2.html.erb
<p id="notice"><%= notice %></p>

<h1>Events index 2</h1>


<div class="row ">
<% @events.each do |event| %>
  <div class="col-sm-12 col-md-12 col-lg-6" style="overflow: auto;">
    <div class="card bg-light mb-3">
      <div class="card-header text-center header-color"><%= event.university.nombre %></div>
      <div class="card-body">
        <h5 class="title"><%= event.nombre %></h5>
        <p class="card-text">
          <b>Descripción:</b> <%= event.descripcion %> <br>
          <b>Lugar:</b> <%= event.lugar %> <br>
          <b>Fecha:</b> <%= event.fecha %> <br>
         
          <center>
          <a href="http://<%= event.link %>" target="blank" class="btn btn-success" style="width: 100%;font-size: 18px;" >Más información</a>
          </center>
        </p>
      </div>
    </div>
  </div>
<% end %>
</div>
<br>

app/views/events/loadCategories.js.erb
$("#nameEvent").empty()

$("#nameEvent").append("<%=@event.nombre%>")
$("#tableCategories").empty()
$("#tableCategories").append("<thead><tr>"+
	                           "<th width='40%'>Nombre</th>"+
	                          
                             "<th width='10%'></th>"+
	                           "</tr></thead><tbody>");
 <%i=1%>
 <% @categorias.each do |categoria|%>
 
 $("#tableCategories").append("<tr>"+
 	                            "<td width='40%'><%= categoria.nombre %></td>"+
 	                                                         
                              "<td>"+
                                "<% categoryEvent=CategoryEvent.find_by(category_id: categoria.id,event_id: @event.id) %> "+
                                "<%if categoryEvent!=nil %>"+
        	                    "<input type='checkbox' class='filled-in' id='categoryEvent<%=categoria.id%>' onChange='saveEventCategory(this,<%=@event.id%>,<%=categoria.id%>)'  checked/>"+
        	                    "<%else%>"+
        	                    "<input type='checkbox' class='filled-in' id='categoryEvent<%=categoria.id%>' onChange='saveEventCategory(this,<%=@event.id%>,<%=categoria.id%>)'  />"+
        	                    "<%end%>"+
        	                    "<label for='categoryEvent<%=categoria.id%>'></label>"+
                                "</td>"+
 	                            "<td width='10%'></td>"+
 	                            "</tr>");
 <%i+=1%>
 <%end%>
$("#tableCategories").append("</tbody>");

app/views/events/new.html.erb
<h1>Nuevo evento</h1>

<%= render 'form', event: @event %>
<div class="" style="padding: 2em">
<%= link_to 'Back', events_path, :class=>'btn btn-secondary btn-lg float-center' %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container py-5">
   <div class="row">
      <div class="col-md-12">
         <div class="row">
            <div class="col-md-6 mx-auto">
               <!-- form card login -->
               <div class="card rounded-0">
                  <div class="card-header">
                     <h3 class="mb-0">Formulario</h3>
                  </div>
                  <div class="card-body">
<p>
  <strong>Id event:</strong>
  <%= @event.id_event %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @event.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @event.descripcion %>
</p>

<p>
  <strong>Lugar:</strong>
  <%= @event.lugar %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @event.fecha %>
</p>


<p>
  <strong>Link:</strong>
  <%= @event.link %>
</p>

<%= link_to 'Edit', edit_event_path(@event), :class=>'btn btn-warning btn-lg float-center' %> |
<%= link_to 'Back', events_path, :class=>'btn btn-secondary btn-lg float-center' %>
</div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>