config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :events, except: [:show]
  resources :universities 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root :to => 'universities#index'
  get 'universities/index2'
  get 'events/saveEventCategory'
  get 'events/loadCategories'
  get 'events/:id', to: 'events#show'
  
  
  
end

app/models/university.rb
class University < ApplicationRecord
	has_many :events
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  load_and_authorize_resource
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    @events = Event.all.order(fecha: :asc)
    @universities = University.all
    @idUser=current_user
    @universities2 = University.where(id_universidad: @idUser.email)
    @categorias=Category.all
  end

  def index2
    @events = Event.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_params
      params.require(:university).permit(:id_universidad, :nombre, :direccion, :telefono, :ciudad, :departamento)
    end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/universities/_form.html.erb
<div class="container py-5">
   <div class="row">
      <div class="col-md-12">
         <div class="row">
            <div class="col-md-6 mx-auto">
               <!-- form card login -->
               <div class="card rounded-0">
                  <div class="card-header">
                     <h3 class="mb-0">Formulario</h3>
                  </div>
                  <div class="card-body">
<%= form_with(model: university, local: true) do |form| %>
  <% if university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% if  @current_user.role == 'admin'%>
    <%= form.label :Correo %>
    <%= form.text_field :id_universidad, id: :university_id_universidad, :class=>'form-control form-control-lg rounded-0'%>
    <% else %>
    <%= form.label :Correo %>
    <%= form.text_field :id_universidad, id: :university_id_universidad, :class=>'form-control form-control-lg rounded-0', :disabled=>'disabled' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :university_nombre, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :dirección %>
    <%= form.text_field :direccion, id: :university_direccion, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :teléfono %>
    <%= form.text_field :telefono, id: :university_telefono, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :ciudad %>
    <%= form.text_field :ciudad, id: :university_ciudad, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="form-group">
    <%= form.label :departamento %>
    <%= form.text_field :departamento, id: :university_departamento, :class=>'form-control form-control-lg rounded-0' %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", :class=>'btn btn-success btn-lg float-right' %>
  </div>
<% end %>
</div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/universities/edit.html.erb
<%= render 'form', university: @university %>
<center> 		
<div class="" style="padding: 2em">
<%= link_to 'Mostrar', @university, :class=>'btn btn-secondary btn-lg float-center' %> 
<%= link_to 'Atrás', universities_path, :class=>'btn btn-warning btn-lg float-center' %>
</div>
</center>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<% if @idUser.role=="university" %>
  <h1>Universidad</h1>

    <table class="table  table-sm">
      <thead class="thead-dark">
        <tr>
          <th>Eventos</th>
          <th>Nombres</th>
          <th>Direcciones</th>
          <th>Teléfonos</th>
          <th>Ciudades</th>
          <th>Departamentos</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @universities2.each do |university| %>
          <tr>
           <!-- <td><%= university.id_universidad %></td>-->
            <td><%= link_to 'Ver eventos', :controller=>'events', :action=>'index', :idUniversity=>university.id %></td>
            <td><%= university.nombre %></td>
            <td><%= university.direccion %></td>
            <td><%= university.telefono %></td>
            <td><%= university.ciudad %></td>
            <td><%= university.departamento %></td>
            <td><%= link_to 'Show', university, :class=>'btn btn-success'  %></td>
            <td><%= link_to 'Edit', edit_university_path(university), :class=>'btn btn-warning'  %></td>
            
          </tr>
        <% end %>
      </tbody>
    </table>



<% elsif @idUser.role=="admin" %>
    <p>Administrador</p>
    <h1>Universidades</h1>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Id universidades</th>
          <th>Nombres</th>
          <th>Direcciones</th>
          <th>Teléfonos</th>
          <th>Ciudades</th>
          <th>Departamentos</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @universities.each do |university| %>
          <tr>
           <!-- <td><%= university.id_universidad %></td>-->
            <td><%= link_to university.id_universidad, :controller=>'events', :action=>'index', :idUniversity=>university.id %></td>
            <td><%= university.nombre %></td>
            <td><%= university.direccion %></td>
            <td><%= university.telefono %></td>
            <td><%= university.ciudad %></td>
            <td><%= university.departamento %></td>
            <td><%= link_to 'Show', university, :class=>'btn btn-info' %></td>
            <td><%= link_to 'Edit', edit_university_path(university), :class=>'btn btn-warning' %></td>
            <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>
  <%= link_to 'Nueva Universidad', new_university_path, :class=>'btn btn-success btn-lgr'%>

<% else %>
  <p>Invitado</p>

  <div class="row ">
    <% @events.each do |event| %>
      <div class="col-sm-12 col-md-12 col-lg-6" style="overflow: auto;">
        <div class="card bg-light mb-3">
          <div class="card-header text-center header-color"><%= event.university.nombre %></div>
          <div class="card-body">
            <h5 class="title"><%= event.nombre %></h5>
            <p class="card-text">
              <b>Descripción:</b> <%= event.descripcion %> <br>
              <b>Lugar:</b> <%= event.lugar %> <br>
              <b>Fecha:</b> <%= event.fecha %> <br>
               <b>Categorias:</b> 

          <% @categorias.each do |categoria|%>

            <% categoryEvent=CategoryEvent.find_by(category_id: categoria.id,event_id: event.id) %>
            <%if categoryEvent!=nil %>
             - <%= categoria.nombre %> 
            <%end%>

          <%end%>
              <center>
              <a href="http://<%= event.link %>" target="blank" class="btn btn-success" style="width: 100%;font-size: 18px;" >Más información</a>
              </center>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/universities/index2.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>


<div class="row ">
<% @events.each do |event| %>
  <div class="col-sm-12 col-md-12 col-lg-6" style="overflow: auto;">
    <div class="card bg-light mb-3">
      <div class="card-header text-center header-color"><%= event.university.nombre %></div>
      <div class="card-body">
        <h5 class="title"><%= event.nombre %></h5>
        <p class="card-text">
          <b>Descripción:</b> <%= event.descripcion %> <br>
          <b>Lugar:</b> <%= event.lugar %> <br>
          <b>Fecha:</b> <%= event.fecha %> <br>
          <b>Categoria:</b> <%= event.categoria %> <br><br>
          <center>
          <a href="http://<%= event.link %>" target="blank" class="btn btn-success" style="width: 100%;font-size: 18px;" >Más información</a>
          </center>
        </p>
      </div>
    </div>
  </div>
<% end %>
</div>
<br>

app/views/universities/new.html.erb
<h1>Nueva Universidad</h1>

<%= render 'form', university: @university %>
<center> 		
<div class="" style="padding: 2em">
<%= link_to 'Atrás', universities_path, :class=>'btn btn-warning btn-lg' %>
</div>
</center>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container py-5">
   <div class="row">
      <div class="col-md-12">
         <div class="row">
            <div class="col-md-6 mx-auto">
               <!-- form card login -->
               <div class="card rounded-0">
                  <div class="card-header">
                     <h3 class="mb-0">Formulario</h3>
                  </div>
                  <div class="card-body">
<p>
  <strong>Correo:</strong>
  <%= @university.id_universidad %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @university.nombre %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @university.direccion %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @university.telefono %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @university.ciudad %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @university.departamento %>
</p>

<%= link_to 'Edit', edit_university_path(@university), :class=>'btn btn-warning btn-lg float-center'  %> |
<%= link_to 'Back', universities_path, :class=>'btn btn-secondary btn-lg float-center'  %>
</div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>